apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-2
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

#  todo use local/production
#  storageClassName: do-block-storage
