kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    app: django
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
